"""Generate the noindex execution entry from the shared program-trace HTML."""
from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "program-trace" / "index.html"
OUTPUT = ROOT / "program-trace" / "run.html"
LIBRARY_URL = "https://mei-chan-nel.com/program-trace/"


def render_runner() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    robots = '<meta name="robots" content="index, follow" />'
    if source.count(robots) != 1:
        raise ValueError("The trace library must have exactly one index, follow robots tag.")
    result = source.replace(robots, '<meta name="robots" content="noindex, follow" />', 1)
    result = result.replace(LIBRARY_URL, LIBRARY_URL + "run.html")
    result = result.replace(
        '<section id="library-view" aria-labelledby="library-title">',
        '<section id="library-view" aria-labelledby="library-title" hidden>',
        1,
    )
    return result.replace(
        '<!doctype html>',
        '<!doctype html>\n<!-- Generated by scripts/build_program_trace_pages.py; edit program-trace/index.html. -->',
        1,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check the generated execution entry without writing.")
    args = parser.parse_args()
    expected = render_runner()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("program-trace/run.html is out of date. Run python scripts/build_program_trace_pages.py.")
            return 1
        print("Program trace execution entry is synchronized and noindex.")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
        print("Generated program-trace/run.html with noindex, follow.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
