from __future__ import annotations

import json
from html.parser import HTMLParser
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TERMS_ROOT = ROOT / "terms"
OUTPUT_PATH = ROOT / "assets" / "term-guides.js"
TAG_META = "study-atlas-term-tag"
SUMMARY_META = "study-atlas-term-summary"


class TermMetaParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.values: dict[str, str] = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "meta":
            return
        attributes = {name.lower(): value for name, value in attrs if value is not None}
        name = attributes.get("name", "").strip()
        if name not in {TAG_META, SUMMARY_META}:
            return
        self.values[name] = attributes.get("content", "").strip()


def read_term_meta(path: Path) -> tuple[str, str]:
    parser = TermMetaParser()
    parser.feed(path.read_text(encoding="utf-8"))
    tag = parser.values.get(TAG_META, "").strip()
    summary = parser.values.get(SUMMARY_META, "").strip()
    if not tag:
        raise ValueError(f"{path.relative_to(ROOT)}: {TAG_META} is required")
    if not summary:
        raise ValueError(f"{path.relative_to(ROOT)}: {SUMMARY_META} is required")
    return tag, summary


def build_registry() -> dict[str, dict[str, str]]:
    registry: dict[str, dict[str, str]] = {}
    if not TERMS_ROOT.exists():
        return registry

    for path in sorted(TERMS_ROOT.glob("*/index.html")):
        tag, summary = read_term_meta(path)
        if tag in registry:
            raise ValueError(f"Duplicate term tag: {tag}")
        slug = path.parent.name
        registry[tag] = {
            "url": f"/terms/{slug}/",
            "summary": summary,
        }
    return registry


def render(registry: dict[str, dict[str, str]]) -> str:
    payload = json.dumps(
        registry,
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
    )
    return (
        "// Generated by scripts/generate_term_guides.py. Do not edit by hand.\n"
        f"window.StudyAtlasTermGuides = Object.freeze({payload});\n"
    )


def main() -> None:
    registry = build_registry()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(registry), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} with {len(registry)} term guide(s).")


if __name__ == "__main__":
    main()
